# Generated by Django 3.2.8 on 2021-12-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('age_bit_length', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('weight_bit_length', models.IntegerField()),
                ('height', models.IntegerField()),
                ('height_bit_length', models.IntegerField()),
                ('hospital', models.CharField(max_length=200)),
            ],
        ),
    ]
