# Generated by Django 3.2.8 on 2022-01-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.CharField(max_length=300),
        ),
    ]
